version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - apt-get update
      - apt-get install -y docker.io

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-south-1)

  build:
    commands:
      # Build the Docker image
      - echo "Building Docker image..."
      - export IMAGE_REPO_NAME="my-flask-app"
      - export IMAGE_TAG=$(date +'%Y-%m-%d_%H%M')
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 730335356144.dkr.ecr.ap-south-1.amazonaws.com/image-repo1:$IMAGE_TAG

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 730335356144.dkr.ecr.ap-south-1.amazonaws.com/image-repo1:$IMAGE_TAG
      - echo "Docker image pushed successfully to Amazon ECR"

