version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y python3-pip python3.12-venv
      - python3 -m venv myenv
      - source myenv/bin/activate
      - pip3 install -r requirements.txt


  build:
    commands:
      - echo Running unit tests...
      # Add commands here to run your unit tests if you have any

  # post_build:
  #   commands:
  #     - echo Installing Docker...
  #     - apt-get install -y docker.io
  #     - echo Building Docker image...
  #     - docker build -t flask-app .
  #     - echo Tagging Docker image...
  #     - docker tag flask-app:latest YOUR_ECR_REGISTRY_URL/flask-app:latest
  #     - echo Pushing Docker image to ECR...
  #     - $(aws ecr get-login --no-include-email --region YOUR_REGION)
  #     - docker push YOUR_ECR_REGISTRY_URL/flask-app:latest

artifacts:
  files:
    - '**/*'
  discard-paths: no

