version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "[Install] Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "[Pre-Build] Executing pre-build commands..."

  build:
    commands:
      - echo "[Build] Building and testing the Flask app..."
      - python -m unittest discover  # Replace with your test command if applicable

  post_build:
    commands:
      - echo "[Post-Build] Executing post-build commands..."

artifacts:
  files: '**/*'

